application: hotornotblitz
version: 9
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: hotornot.app

libraries:
- name: jinja2
  version: latest
